### ISSUE TITLE
remove it, then error

### ISSUE THREAD

**Issue by jiangyuan** [MiroHibler/sublime-keymaps#20]
remove this package, start sublime again, and it error:
>Error loading syntax file: 
>"path/to/cheat_sheet.hidden-tmLanguage": Unable to open Packages/keymaps/cheat_sheet.hidden-tmLanguage

**Comment by MiroHibler** [comment]
How did you remove it? Via command palette or manually (deleting it from file system)?

**Comment by jiangyuan** [comment]
Just via command palette.
Forget it, I reinstall my sublime.
