### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by mswanson** [MiroHibler/sublime-keymaps#22]
noticed that there have been no updates since Jan 2014 and it is no longer listed on packagecontrol.io. Just curious if it has been abandoned and if there are similar packages that you would recommend.

**Comment by Miw0** [comment]
I came here from the Package Control website, so I guess it is still listed (or maybe again)?
https://packagecontrol.io/packages/Keymaps

**Comment by MiroHibler** [comment]
Hey guys, I'm still here but being awfully busy lately... :(

I initially made this as an exercise while learning Python (Django) and started to work with ST.

I do have some ideas (nothing spectacular ;) but struggling to find some spare time to do it

**Comment by pykong** [comment]
Sorry, for necroposting but I wanted to prevent a duplicate.

@MiroHibler Thanks for putting this nice little gem up!
If you no longer want to maintain it (alone). Maybe you would want to give others push access or even transfer ownership of this repo. This seems to be the most logical step to me.

**Comment by MiroHibler** [comment]
My sincere apologies to everyone waiting to get some updates to this repo, but I do not intend to maintain it anymore since I moved to Atom long time ago and not using ST at all anymore.

But all contributions are welcome, so let me know if you're interested and I'll add you to the repo as a collaborator.

Thanks for your patience and understanding!

**Comment by pykong** [comment]
@MiroHibler Thanks for your response and your offer for collaboration.
Yes. please grant me push access. 

I am going to use those newly granted powers to:
- Drop ST2 support 
- Cleanup the code base
- Implement export keymaps to MarkDown

**Comment by MiroHibler** [comment]
Invited :)

**Comment by pykong** [comment]
@MiroHibler Many thanks for your trust.
I am closing this issue, since the initial question 'Is this repo still being maintained?' has been answered. :)
