### ISSUE TITLE
Can't load cheat_sheet.hidden-tmLanguage

### ISSUE THREAD

**Issue by y0k4i-1337** [MiroHibler/sublime-keymaps#29]
Whenever I run "Cheat Sheet" command I get an error about `cheat_sheet.hidden-tmLanguage`.
 I am installing with Package Control and I found that the package was actually installed in "Installed Packages" directory, not "Packages".
However, copying or moving the package file into Packages dir did not solve the problem.

I am running Sublime Text Build 3211 on Arch Linux.

Any ideias on how to solve this issue (at least a workaround)?

![2020-04-30_16-07_1](https://user-images.githubusercontent.com/7395296/80753139-24fdd880-8b03-11ea-876e-9e3e06dc0058.png)

**Comment by vengin** [comment]
Have the same issue on two different Win10 PCs (Sublime 3.2.2 Build 3211).

**Comment by JianhuiShi** [comment]
I install `PackageResourceViewer` and extract `keymaps` into `Packages` directory and then it works fine.
